### ISSUE TITLE
Add TypeScript and Flow type definitions

### ISSUE THREAD

**Issue by cometkim** [cometkim/react-hot-reload.macro#1]
- Add `index.d.ts` for TypeScript support
- Add Flow comment annotations for Flow support

**Comment by harrysolovay** [comment]
I attempted adding a simple module declaration to no avail. There's something about how babel macros get evaluated by the TypeScript server... it's unexpected. Any tips on how to avoid the error (I don't care about perfect type safety... just getting it running)

**Comment by cometkim** [comment]
@harrysolovay I think... It should re-export the RHL's type, because this macro will be replaced into the usual RHL syntax.

so it (ts/flow both) would be like:

```ts
import {someType} from 'react-hot-loader'

declare module 'react-hot-realod.macro' {
  export default someType;
}
```
