### ISSUE TITLE
Does not pick up state additions

### ISSUE THREAD

**Issue by imornar** [cometkim/react-hot-reload.macro#4]
When  something is added to Component state e.g `state={counter: 3}`, and referenced inside JSX as `{this.state.counter}` it HMR does not pick it up until user manually refresh page. 
Afterwards it works as expected, until you add something else inside state, then again manual refresh is required.
shouldn't it be used in `src/index.js` file, like so:
```
import hot from 'react-hot-reload.macro';

ReactDOM.render(<App/>, document.getElementById('root'));
hot(module)(App);
```
this fixes above issue

**Comment by cometkim** [comment]
Hey @imornar, thank you for reporting.

That is a known [limitation by RHL](https://github.com/gaearon/react-hot-loader#limitations)

> (that's the goal) React-Hot-Loader would not update any object, including component state.

If you rendered plain `<App/>` component that isn't wrapped by RHL so it will work with [Webpack's plain reloading](https://blog.isquaredsoftware.com/2017/08/blogged-answers-webpack-hmr-vs-rhl/). RHL only replaces webpack's refreshing behavior with redrawing the body tag.

**Comment by cometkim** [comment]
You can get same effect with `hot(module)()` without `App`

But anyway I think it's an useful workaround for some cases :)
