### ISSUE TITLE
just curious - what is this used for?

### ISSUE THREAD

**Issue by gcloeval** [cometkim/react-hot-reload.macro#7]
Hey I somehow stumbled on this one when reading about babel-plugin-macros here https://github.com/jgierer12/awesome-babel-macros

I am just curious as there is not much in the readme - when/why would you use this? Doesnt CRA2 already to hot reloading? What problem does this solve?

**Comment by AK-101111** [comment]
No create-react-app does not support hot module reload out of the box. 
It only works for css changes. 
For HMR people either eject, fork or wire around it with projects such as react-app-rewired

**Comment by cometkim** [comment]
RHL is a little bit different from webpack's plain reloading feature. here's a good post about it 

https://blog.isquaredsoftware.com/2017/08/blogged-answers-webpack-hmr-vs-rhl/

And, @AK-101111, I just released a new version of this with RHL 4.7, now it would work for js changes properly. (it detects file change after saving more than **two times**, I'm not sure it's known issue of RHL... or maybe related with react-:fire:-dom)
